name: Android CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
    branches:
      - main
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
env:
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get source code
      - uses: actions/checkout@v4.2.2
      # Set up Java
      - name: set up OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-alternatives --auto java
      # Build the app
      - name: Build
        run: ./gradlew assembleDebug
      # Stop Gradle daemon
      - name: Stop gradle daemon
        run: ./gradlew --stop
      # Cache
      - uses: actions/cache/save@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  check-translations:
    runs-on: ubuntu-latest
    steps:
      # Get source code
      - uses: actions/checkout@v4.2.2
      # Check translations
      - name: Fail on bad translations
        run: if grep -ri "&lt;xliff" app/src/main/res/values*/strings.xml; then echo "Invalidly escaped translations found"; exit 1; fi
  instrumented-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        api-level: [21, 34]
        flavor: [Foss, Gplay]
    steps:
      # Get source code
      - uses: actions/checkout@v4.2.2
      # Restore cache
      - uses: actions/cache/restore@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Set up Java
      - name: set up OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-alternatives --auto java
      # Instrumented tests
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run instrumented tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connected${{ matrix.flavor }}DebugAndroidTest
  lint:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        flavor: [Foss, Gplay]
    steps:
      # Get source code
      - uses: actions/checkout@v4.2.2
      # Restore cache
      - uses: actions/cache/restore@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Set up Java
      - name: set up OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-alternatives --auto java
      # Lint
      - name: Check lint
        run: ./gradlew lint${{ matrix.flavor }}Debug
  spotbugs:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        flavor: [Foss, Gplay]
    steps:
      # Get source code
      - uses: actions/checkout@v4.2.2
      # Restore cache
      - uses: actions/cache/restore@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Set up Java
      - name: set up OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-alternatives --auto java
      # Spotbugs
      - name: SpotBugs
        run: ./gradlew spotbugs${{ matrix.flavor }}Debug
  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        flavor: [Foss, Gplay]
    steps:
      # Get source code
      - uses: actions/checkout@v4.2.2
      # Restore cache
      - uses: actions/cache/restore@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Set up Java
      - name: set up OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-alternatives --auto java
      # Unit test
      - name: Run unit tests
        run: timeout 5m ./gradlew test${{ matrix.flavor }}DebugUnitTest || { ./gradlew --stop && timeout 5m ./gradlew test${{ matrix.flavor }}DebugUnitTest; }
