name: 'Close issues and PRs needing info for too long'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: -1
          days-before-close: 90
          close-issue-message: 'This issue is missing necessary information and cannot be worked on in its current state. It has therefore been closed to keep the issue tracker clean. If you have more information, feel free to reopen it.'
          close-pr-message: 'This PR is missing necessary information and cannot be merged in its current state. It has therefore been closed to keep the issue tracker clean. If you have more information, feel free to reopen it.'
          only-labels: 'state: needs info'
          stale-issue-label: 'state: needs info'
          stale-pr-label: 'state: needs info'
          remove-stale-when-updated: false
          enable-statistics: true
